name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request: {}
permissions:
  checks: write
  pull-requests: write  
env:
  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "temurin"
jobs:
  test:
    name: "Test and Collect Results"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "${{ env.JAVA_DISTRIBUTION }}"
          java-version: "${{ env.JAVA_VERSION }}"
      - name: Run unit tests
        run: |
          make -C src unit-test
        id: unit-tests
      - name: Run integration tests
        run: |
            make -C src smoke-test
        id: integration-tests
      - name: Run specification tests
        run: |
          make -C src spec-test
        id: spec-tests
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: Test Results
          path: |
            **/*_junit-report.xml
  event_file:
    name: "Upload Results to Event File"
    runs-on: ubuntu-20.04
    needs: test
    steps:
    - name: Upload
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: Test Results Event
        path: ${{ github.event_path }}
